apiVersion: v1
kind: Secret
metadata:
    name: db-credentials
    namespace: demo
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:TYheXYuoBiPtSBe3xOsfuVMHdL4ufs9kAUPR+cXQ0Uf6zoT4k4xsEUoGyGvrRxF61+2oWAdqsrwLdnPAOP/GajwodmaY2diXxfq3zRCntvM5dRZbjwIXlH2mWEmXmHtHwhIeWm+m28lN3q0cwX85x9t/RJpYvLW6oC8yu9k6vVt5rpbKRYdJuS5P0nrR,iv:5cbIDnPURGBDWJ5EvAYy+Ak5FBycqyFN0nqvhgkZvuU=,tag:66etqiFSIN0QNV4QCWGdoQ==,type:str]
sops:
    age:
        - recipient: age1u7a5swnulhfm8a0artwuhpargcqc7ererf9a3rffcjj40cx06cas28nmce
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNSs2SkViM0tlVm5GNVZ1
            S1JXMEtKOTR4T3pBM0RxbXlPUHNiV3JvN0NvCnk1bTJMb0hWZmRLcDQrSjR1V08x
            cVFGcThzYmFjRkpQUEdYcmpiblFJUk0KLS0tIGpzWDZTUHQrVzg3QWY1MHQ5eEVU
            QXBtdGNFSXVERndpbWJhdG9XclFyTUEKtvjcqvNji4lq0tIYKk2n9Fcq8ZZiLVjs
            YrN9RWcI/+YPeKs+QjfCkT+9KJIJ51e6vtidv5GlUnFZN1khAKwUZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T17:54:31Z"
    mac: ENC[AES256_GCM,data:pMzBLm05binSCsTc+lo5hyqz17V8YqQEUEJa7oOTSMIx6Stb/np8SrDxXJ4L9FH+Dxs+JlgzhPvSD3WcTdRSGrbzJyY495iNGT/+UaDh5EqLdVUZz6PHUXBx3MDmJ5zKG0diSif1uBWzXOZZY41mjTjqSIrhRGxhNNNy402IYSY=,iv:TL8eK+iDjQUhFK9s9dwCfymqu95UQosx1N2Otkh5G5o=,tag:gfE3+kuKChJXJr2F6KUO2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
